// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-YzhTJs2Anij8nCBSpEjPehPJ3AbVsK8',
    appId: '1:995078348476:web:859b9b73ef07816c9ebab9',
    messagingSenderId: '995078348476',
    projectId: 'madmon-7bf80',
    authDomain: 'madmon-7bf80.firebaseapp.com',
    storageBucket: 'madmon-7bf80.firebasestorage.app',
    measurementId: 'G-5VLRSCTE1Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfqX7g3BEdvw9rFg8wsqv8-r2G-0K6IOk',
    appId: '1:995078348476:android:37732b6c68c418de9ebab9',
    messagingSenderId: '995078348476',
    projectId: 'madmon-7bf80',
    storageBucket: 'madmon-7bf80.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgdd2HQX8_DiOBY5DtXt83o1u3K4fcDyc',
    appId: '1:995078348476:ios:34876bb826f7276b9ebab9',
    messagingSenderId: '995078348476',
    projectId: 'madmon-7bf80',
    storageBucket: 'madmon-7bf80.firebasestorage.app',
    iosBundleId: 'com.example.madmon',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC-YzhTJs2Anij8nCBSpEjPehPJ3AbVsK8',
    appId: '1:995078348476:web:32daa5564d43c43e9ebab9',
    messagingSenderId: '995078348476',
    projectId: 'madmon-7bf80',
    authDomain: 'madmon-7bf80.firebaseapp.com',
    storageBucket: 'madmon-7bf80.firebasestorage.app',
    measurementId: 'G-C76Z4BSY92',
  );

}